<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Users[
        <!ELEMENT Users (User)+>
        <!ELEMENT User (Email,Nickname,Password,Cart) >
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Cart (Goods)+>
        <!ELEMENT Goods (Name,Type,Description,Price,Availability)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Type (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>
        <!ELEMENT Availability (#PCDATA)>
] >
<Users>
    <User>
        <Email>asd123@yandex.ru</Email>
        <Nickname>VasI9123</Nickname>
        <Password>qwerty</Password>
        <Cart>
            <Goods>
                <Name>iPhone X</Name>
                <Type>Smartphone</Type>
                <Description>Last iPhone by apple</Description>
                <Price>$999</Price>
                <Availability>In stock</Availability>
            </Goods>
        </Cart>
    </User>
    <User>
        <Email>qwerty123@yandex.ru</Email>
        <Nickname>George1337</Nickname>
        <Password>qwerty</Password>
        <Cart>
            <Goods>
                <Name>Beats Studio HD</Name>
                <Type>Headphones</Type>
                <Description>Headphones by Dr.Dre</Description>
                <Price>$299</Price>
                <Availability>In stock</Availability>
            </Goods>
            <Goods>
                <Name>Macbook 2018</Name>
                <Type>Laptop</Type>
                <Description>New laptop by apple</Description>
                <Price>$1799</Price>
                <Availability>Pre-order</Availability>
            </Goods>
        </Cart>
    </User>
    <User>
        <Email>gigalo3@yandex.ru</Email>
        <Nickname>Gigalo3</Nickname>
        <Password>qwerty</Password>
        <Cart>
            <Goods>
                <Name>Toshiba Canvio 1tb</Name>
                <Type>External hdd</Type>
                <Description>Best external hdd in 2017</Description>
                <Price>$69</Price>
                <Availability>In stock</Availability>
            </Goods>
        </Cart>
    </User>
</Users>