<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Students [<!ELEMENT Students (Student)+>
        <!ELEMENT Student (Univer,Kurs,Facultet,Goods,Price) >
        <!ELEMENT Univer (#PCDATA)>
        <!ELEMENT Kurs (#PCDATA)>
        <!ELEMENT Facultet (#PCDATA)>
        <!ELEMENT Goods (Product)+>
        <!ELEMENT Product (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>] >
<Students>
    <Student>
        <Univer>БНТУ</Univer>
        <Kurs>1</Kurs>
        <Facultet>ЭФ</Facultet>
        <Goods>
            <Product>Контрольная по химии</Product>
            <Product>Контрольная по математике</Product>
        </Goods>
        <Price>35 у.е.</Price>
    </Student>
    <Student>
        <Univer>БГУИР</Univer>
        <Kurs>2</Kurs>
        <Facultet>ИТ</Facultet>
        <Goods>
            <Product>Контрольная по химии</Product>
        </Goods>
        <Price>20 у.е.</Price>
    </Student>
</Students>