<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Persons [
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email,Nickname,Password,Ads) >
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Description,Carrying,Volume,Tariff)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Carrying (#PCDATA)>
        <!ELEMENT Volume (#PCDATA)>
        <!ELEMENT Tariff (#PCDATA)>

]>
<Persons>
    <Person>
        <Email>lorry@fraht.com</Email>
        <Nickname>GrazyDriver</Nickname>
        <Password>h879586k</Password>
        <Ads>
            <Ad>
                <Description>
                    Грузоперевозки по Рб и РФ
                </Description>
                <Carrying>20</Carrying>
                <Volume>120</Volume>
                <Tariff>1.5$ за километр</Tariff>
            </Ad>
            <Ad>
                <Description>
                    Грузоперевозки по Рб
                </Description>
                <Carrying>5</Carrying>
                <Volume>50</Volume>
                <Tariff>0.75$ за километр</Tariff>
            </Ad>
        </Ads>
    </Person>
    <Person>
        <Email>truck@fraht.com</Email>
        <Nickname>NorthDriver</Nickname>
        <Password>78o52i89</Password>
        <Ads>
            <Ad>
                <Description>
                    Грузоперевозки по Европе
                </Description>
                <Carrying>20</Carrying>
                <Volume>120</Volume>
                <Tariff>1.65$ за километр</Tariff>
            </Ad>
            <Ad>
                <Description>
                    Грузоперевозки по Рб и РФ
                </Description>
                <Carrying>10</Carrying>
                <Volume>80</Volume>
                <Tariff>0.95$ за километр</Tariff>
            </Ad>
        </Ads>

    </Person>
</Persons>
