=== IrinaSendetskaya/JD2017-12-16/src/by/it/karpeichyk/jd02_09/Persons.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns ="http://www.w3.org/2001/XMLSchema"
         targetNamespace="http://jd02_09.karpeichyk.it.by"
          xmlns:tns="http://jd02_09.karpeichyk.it.by"
          elementFormDefault="qualified">
    <element name="Persons">
        <complexType>
            <sequence>
                <element name="Person"
                         type="tns:Person"
                         maxOccurs="unbounded">

                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Person">
        <sequence>
            <element name="Email" type="string"/>
            <element name="Nickname" type="ID"/>
            <element name="Password" type="string"/>
            <element name="Ads" type="tns:Ads"/>
        </sequence>
    </complexType>

    <complexType name="Ads">
        <sequence>
            <element name="Ad" type="tns:Ad"
               minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Ad">
        <all>
            <element name="Description" type="string"/>
            <element name="Carrying" type="double"/>
            <element name="Volume" type="double"/>
            <element name="Tariff" type="string"/>
        </all>
    </complexType>
</schema>

=== IrinaSendetskaya/JD2017-12-16/src/by/it/karpeichyk/jd02_10/PersonsplusXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://jd02_09.karpeichyk.it.by Persons.xsd"
        xmlns="http://jd02_09.karpeichyk.it.by">

        <Person>
            <Email>lorry@fraht.com</Email>
            <Nickname>GrazyDriver</Nickname>
            <Password>h879586k</Password>
            <Ads>
                <Ad>
                    <Description>
                        Грузоперевозки по Рб и РФ
                    </Description>
                    <Carrying>20</Carrying>
                    <Volume>120</Volume>
                    <Tariff>1.5$ за километр</Tariff>
                </Ad>
                <Ad>
                    <Description>
                        Грузоперевозки по Рб
                    </Description>
                    <Carrying>5</Carrying>
                    <Volume>50</Volume>
                    <Tariff>0.75$ за километр</Tariff>
                </Ad>
            </Ads>

        </Person>
        <Person>
            <Email>truck@fraht.com</Email>
            <Nickname>NorthDriver</Nickname>
            <Password>78o52i89</Password>
            <Ads>
                <Ad>
                    <Description>
                        Грузоперевозки по Европе
                    </Description>
                    <Carrying>20</Carrying>
                    <Volume>120</Volume>
                    <Tariff>1.65$ за километр</Tariff>
                </Ad>
                <Ad>
                    <Description>
                        Грузоперевозки по Рб и РФ
                    </Description>
                    <Carrying>10</Carrying>
                    <Volume>80</Volume>
                    <Tariff>0.95$ за километр</Tariff>
                </Ad>
            </Ads>

        </Person>

</Persons>
