<?xml version='1.1' encoding='uTF-8' standalone='yes'?>
<!DOCTYPE users [
        <!ELEMENT users (user)+>
        <!ELEMENT user (name, lastName, email, subscriptions)>
        <!ATTLIST user
        login ID #REQUIRED
        password CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT lastName (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT subscriptions (subscription)+>
        <!ELEMENT subscription (publication, period, startsubscription, endsubscription, price)+>
        <!ATTLIST subscription id ID #REQUIRED>
        <!ELEMENT period (#PCDATA)>
        <!ELEMENT startsubscription (#PCDATA)>
        <!ELEMENT endsubscription (#PCDATA)>
        <!ELEMENT publication (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        ]>
<users>                                                                              <!--Подписчики-->
    <user login="Ivan93" password="146asv1">                                         <!--Подписчик-->
        <name>Иван</name>                                                             <!--Имя-->
        <lastName>Иванов</lastName>                                                     <!--Фамилия-->
        <email>asfafaf@bdbl.ru</email>
        <subscriptions>                                                                 <!--Подписки-->
            <subscription id="k43434">
                <publication>Автодайджест</publication>                             <!--Название издания-->
                <period>6</period>                                                  <!--Продолжительность подписки-->
                <startsubscription>01.2018</startsubscription>                       <!--Начало подписного периода-->
                <endsubscription>06.2018</endsubscription>                          <!--Начало подписного периода-->
                <price>9.28</price>                                                           <!--Цена-->
            </subscription>
            <subscription id="k687941">
                <publication>Мир тяжелых моторов</publication>
                <period>2</period>
                <startsubscription>02.2018</startsubscription>
                <endsubscription>03.2018</endsubscription>
                <price>89.8</price>
            </subscription>
        </subscriptions>
    </user>
    <user login="Petr" password="asfas1v8">
        <name>Петр</name>
        <lastName>Петров</lastName>
        <email>afavvs@vava.by</email>
        <subscriptions>
            <subscription id="k2353122">
                <publication>Транспортная безопасность</publication>
                <period>12</period>
                <startsubscription>01.2018</startsubscription>
                <endsubscription>12.2018</endsubscription>
                <price>98.0</price>
            </subscription>
        </subscriptions>
    </user>
</users>