=== IrinaSendetskaya/JD2017-12-16/src/by/it/patsko/jd02_07/TaskB/Books.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Catalog (Category)+>                                  <!--один и более раз-->
        <!ELEMENT Category (CategoryName,Books)+>                       <!--один и более раз-->
        <!ELEMENT CategoryName (#PCDATA)>
        <!ELEMENT Books (Book)*>                                        <!--ноль и более раз-->
        <!ELEMENT Book (Name,Author,Price,BookDetails)*>                <!--ноль и более раз-->
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Author (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>
        <!ELEMENT BookDetails (Publisher,Language,NumOfPages,Edition)>  <!--один обязательный элемент-->
        <!ELEMENT Publisher (#PCDATA)>
        <!ELEMENT Language (#PCDATA)>
        <!ELEMENT NumOfPages (#PCDATA)>
        <!ELEMENT Edition (#PCDATA)>

=== IrinaSendetskaya/JD2017-12-16/src/by/it/patsko/jd02_07/Books+DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Catalog SYSTEM "Books.dtd" >
<Catalog>                                                           <!--католог книг/товаров-->
    <Category>                                                      <!--раздел-->
        <CategoryName>Цифровые технологии</CategoryName>            <!--название раздела-->
        <Books>                                                     <!--книги в разделе-->
            <Book>                                                  <!--конкретная книга-->
                <Name>Java.
                    Эффективное программирование</Name>             <!--название книги-->
                <Author>Джошуа Блох</Author>                        <!--автор-->
                <Price>200</Price>                                  <!--цена товара-->
                <BookDetails>                                       <!--описание книги-->
                    <Publisher>Лори</Publisher>                     <!--издательство-->
                    <Language>русский</Language>                    <!--язык-->
                    <NumOfPages>461</NumOfPages>                    <!--количество страниц-->
                    <Edition>2</Edition>                            <!--издание-->
                </BookDetails>
            </Book>
            <Book>
                <Name>Java 8.
                    Полное руководство</Name>
                <Author>Герберт Шилдт</Author>
                <Price>500</Price>
                <BookDetails>
                    <Publisher>Вильямс</Publisher>
                    <Language>русский</Language>
                    <NumOfPages>1377</NumOfPages>
                    <Edition>9</Edition>
                </BookDetails>
            </Book>
        </Books>
    </Category>

    <Category>
        <CategoryName>Художественная литература</CategoryName>
        <Books>
            <Book>
                <Name>Оно</Name>
                <Author>Стивен Кинг</Author>
                <Price>100</Price>
                <BookDetails>
                    <Publisher>АСТ</Publisher>
                    <Language>русский</Language>
                    <NumOfPages>1245</NumOfPages>
                    <Edition>5</Edition>
                </BookDetails>
            </Book>
        </Books>
    </Category>
</Catalog>
