=== IrinaSendetskaya/JD2017-12-16/src/by/it/viktorbrui/jd02_07/Project/Shop.dtd
<!ELEMENT Persons (Person)+>
<!ELEMENT Person (Nickname, Password, Email, Address, Phone, Orders )>
<!ELEMENT Nickname (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Orders (Order)+>
<!ELEMENT Order (Data, OrderNumber, Products)>
<!ELEMENT Data (#PCDATA)>
<!ELEMENT OrderNumber (#PCDATA)>
<!ELEMENT Products (Product)+>
<!ELEMENT Product (ProductName, Sku, Count, Price, PriceCurrencу)>
<!ELEMENT ProductName (#PCDATA)>
<!ELEMENT Sku (#PCDATA)>
<!ELEMENT Count (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT PriceCurrencу (#PCDATA)>

=== IrinaSendetskaya/JD2017-12-16/src/by/it/viktorbrui/jd02_07/Project/Shop+XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Persons SYSTEM "Shop.dtd" >
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://it.by/Магаз Shop.xsd"
         xmlns="http://it.by/Магаз">
    <Person>
        <Nickname>Adolph</Nickname>
        <Password>CatsRuleTheWorld</Password>
        <Email>IneedPolland@germ.ge</Email>
        <Address>Berlin,Braunau</Address>
        <Phone>01723020732</Phone>
        <Orders>
            <Order>
                <Data>2018-02-08 21:13:48</Data>
                <OrderNumber>002</OrderNumber>
                <Products>
                    <Product>
                        <ProductName>Кусочек Польши</ProductName>
                        <Sku>A4754P3</Sku>
                        <Count>1</Count>
                        <Price>120</Price>
                        <PriceCurrencу>Euro</PriceCurrencу>
                    </Product>
                    <Product>
                        <ProductName>Кусочек России</ProductName>
                        <Sku>A4234D7</Sku>
                        <Count>2</Count>
                        <Price>7005</Price>
                        <PriceCurrencу>RUB</PriceCurrencу>
                    </Product>
                    <Product>
                        <ProductName>Кусочек Пирога</ProductName>
                        <Sku>R2351T1</Sku>
                        <Count>8</Count>
                        <Price>2</Price>
                        <PriceCurrencу>Euro</PriceCurrencу>
                    </Product>
                </Products>
            </Order>
        </Orders>
    </Person>
    <Person>
        <Nickname>Napoleon</Nickname>
        <Password>CatsRuleTheWorld</Password>
        <Email>Vlastelin@franc.fc</Email>
        <Address>Corsica,Aiacho</Address>
        <Phone>334954648744</Phone>
        <Orders>
            <Order>
                <Data>2018-02-08 21:39:14</Data>
                <OrderNumber>003</OrderNumber>
                <Products>
                    <Product>
                        <ProductName>Кусочек Русси</ProductName>
                        <Sku>Z422AS67</Sku>
                        <Count>2</Count>
                        <Price>7005</Price>
                        <PriceCurrencу>Euro</PriceCurrencу>
                    </Product>
                </Products>
            </Order>
        </Orders>
    </Person>
</Persons>
